name: Create Remote

on:
  create

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Terraform init
        working-directory: ./terraform/remote
        run: terraform init

      - name: Terraform variables
        working-directory: ./terraform/remote
        run: |
          cat > pipeline.tfvars <<EOF
          access_key = "${{ secrets.ACCESS_KEY }}"
          secret_key = "${{ secrets.SECRET_KEY }}"
          aws_region = "${{ secrets.AWS_REGION }}"
          bucket_name = "${{ format('slidev-remote-{0}', github.ref_name) }}"
          dynamodb_name = "${{ format('slidev-remote-{0}', github.ref_name) }}"
          EOF

      - name: Terraform apply
        working-directory: ./terraform/remote
        run: terraform apply -auto-approve -var-file=pipeline.tfvars
